FROM openmetadata/server:1.7.2

USER root

RUN apk add --no-cache python3 py3-pip && \
    ln -sf python3 /usr/bin/python && \
    pip install --upgrade pip


RUN pip install --no-cache-dir \
    openmetadata-ingestion==1.7.2.0 

USER om