apiVersion: batch/v1
kind: CronJob
metadata:
  name: openmetadata-snowflake-ingest
  namespace: daap-dev
spec:
  schedule: "*/15 * * * * "
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: metadata
              image: openmetadata/ingestion:1.7.2
              command: ["metadata", "ingest", "-c", "/config/ingest.json"]
              volumeMounts:
                - name: ingest-config
                  mountPath: /config
          restartPolicy: Never
          volumes:
            - name: ingest-config
              configMap:
                name: openmetadata-snowflake-ingest-config