apiVersion: batch/v1
kind: Job
metadata:
  name: openmetadata-ingestion-job
  namespace: daap-dev
spec:
  template:
    spec:
      containers:
        - name: ingestion
          image: openmetadata/ingestion:1.7.1
          command: ["sh", "-c"]
          args:
            - |
              echo '{
                "source": {
                  "type": "snowflake",
                  "serviceName": "daap",
                  "sourceConfig": {
                    "config": {
                      "type": "DatabaseMetadata"
                    }
                  }
                },
                "sink": {
                  "type": "metadata-rest",
                  "config": {
                    "apiEndpoint": "http://20.41.40.141:8585/api"
                  }
                },
                "workflowConfig": {
                  "openMetadataServerConfig": {
                    "hostPort": "http://20.41.40.141:8585/api",
                    "authProvider": "openmetadata",
                    "securityConfig": {
                      "jwtToken": "eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6ImFkbWluIiwicm9sZXMiOlsiQWRtaW4iXSwiZW1haWwiOiJhZG1pbkBvcGVuLW1ldGFkYXRhLm9yZyIsImlzQm90IjpmYWxzZSwidG9rZW5UeXBlIjoiUEVSU09OQUxfQUNDRVNTIiwiaWF0IjoxNzUxOTYzODEyLCJleHAiOjE3NTk3Mzk4MTJ9.j3iOgacmqbeddHPBw4M4ycgAqGSZoffRa1QLO9cLOU3FeLf3FBXBkzO9DhVQ2aOw569tHJ2kUOnTfGXU9MtLAGG0aQ99RBN9HALhsbCAG-PkZd-jIF7et4U3GOEjr5MJjDvNtQkPeZ_s1E_brctjiHXlX0NsoI4C_WFErn3iQ4dXRLFLNo3_VHqx3WrfVZm6-rU0RLRZwFuVmgotvF2fxw7b1VyuG6KyX8MJAufrMW3RWRYsnJQGKdU4KTku_AuPAiJBC29mRb54CDpx9jXXQkzQMdX7TVqPwWWrv5fI0jERmMB7CmujP3ygzL_dz1dVOPoDySDEedHrWUhoU4Vw7g"
                    }
                  }
                }
              }' > /tmp/ingest.json &&
              metadata ingest -c /tmp/ingest.json
      restartPolicy: Never
  backoffLimit: 1
