apiVersion: batch/v1
kind: Job
metadata:
  name: openmetadata-snowflake-ingest
  namespace: daap-dev
spec:
  template:
    spec:
      containers:
        - name: metadata
          image: openmetadata/ingestion:1.7.1
          command: ["metadata", "ingest", "-c", "/config/ingest.json"]
          volumeMounts:
            - name: ingest-config
              mountPath: /config
      restartPolicy: Never
      volumes:
        - name: ingest-config
          configMap:
            name: openmetadata-snowflake-ingest-config
