apiVersion: batch/v1
kind: Job
metadata:
  name: openmetadata-ingestion-job
  namespace: daap-dev
spec:
  template:
    spec:
      containers:
        - name: ingestion
          image: python:3.10
          command: ["sh", "-c"]
          args:
            - |
              pip install "openmetadata-ingestion[pii]==1.7.1 &&
              echo '{
                "source": {
                  "type": "snowflake",
                  "serviceName": "daap",
                  "sourceConfig": {
                    "config": {
                      "type": "DatabaseMetadata"
                    }
                  }
                },
                "sink": {
                  "type": "metadata-rest",
                  "config": {
                    "apiEndpoint": "http://128.85.217.88:8585/api"
                  }
                },
                "workflowConfig": {
                  "openMetadataServerConfig": {
                    "hostPort": "http://128.85.217.88:8585",
                    "authProvider": "basic",
                    "securityConfig": {
                      "username": "admin@open-metadata.org",
                      "password": "admin"
                    }
                  }
                }
              }' > /tmp/ingest.json &&
              metadata ingest -c /tmp/ingest.json
      restartPolicy: Never
  backoffLimit: 1
