apiVersion: batch/v1
kind: Job
metadata:
  name: openmetadata-snowflake-profiler
  namespace: daap-dev
spec:
  template:
    spec:
      containers:
        - name: metadata
          image: openmetadata/ingestion:1.7.1
          command: ["metadata", "ingest", "-c", "/config/profiler.json"]
          volumeMounts:
            - name: profiler-config
              mountPath: /config
      restartPolicy: Never
      volumes:
        - name: profiler-config
          configMap:
            name: openmetadata-snowflake-profiler-config