images:
  airflow:
    repository: "apache/airflow"
    tag: "2.7.3-python3.11"  
    pullPolicy: Always

airflow:
  executor: KubernetesExecutor

  extraEnv:
    - name: AIRFLOW__OPENMETADATA__HOST
      value: "http://openmetadata.daap-dev.svc.cluster.local:8585"
    - name: AIRFLOW__OPENMETADATA__AUTH_PROVIDER
      value: "basic-auth"
    - name: AIRFLOW__OPENMETADATA__API_VERSION
      value: "v1"
    - name: AIRFLOW__API__AUTH_BACKEND
      value: "airflow.api.auth.backend.basic_auth"

  extraVolumeMounts:
    - name: airflow-plugins
      mountPath: /opt/airflow/plugins

  # Scheduler Configuration
  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  # Webserver Configuration
  web:
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"


  # Logs, DAGs, Worker, and Triggerer Persistence
  dags:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: standard

  logs:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: standard

  workers:
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  triggerer:
    persistence:
      enabled: true
      size: 500Mi

  # Database Configuration
  postgresql:
    enabled: false  # Set to true only if  need an internal PostgreSQL DB
