---
apiVersion: v1
kind: Namespace
metadata:
  name: daap-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: daap-dev
type: Opaque
stringData:
  fernet-key: wKoOKzFWfpz7P_YnyFWLq9HQGadsRl3vjIJ6ppYvB-4=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: daap-dev
data:
  airflow.cfg: |
    [core]
    dags_folder = /opt/airflow/dags
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: daap-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:3.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor
            - name: AIRFLOW__CORE__AUTH_MANAGER
              value: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: db+postgresql://airflow:airflow@postgres/airflow
            - name: AIRFLOW__CELERY__BROKER_URL
              value: redis://:@redis:6379/0
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "true"
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "true"
            - name: AIRFLOW__CORE__EXECUTION_API_SERVER_URL
              value: http://airflow-apiserver:8080/execution/
            - name: AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK
              value: "true"
            - name: _PIP_ADDITIONAL_REQUIREMENTS
              value: "openmetadata-ingestion==1.7.1.1 openmetadata-managed-apis==1.7.1.1 apache-airflow-providers-openlineage==2.3.0"
            - name: AIRFLOW_CONFIG
              value: /opt/airflow/config/airflow.cfg
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: logs
              mountPath: /opt/airflow/logs
            - name: config
              mountPath: /opt/airflow/config
            - name: plugins
              mountPath: /opt/airflow/plugins
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: config
          configMap:
            name: airflow-config
        - name: plugins
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: daap-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: daap-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi
