executor: KubernetesExecutor

airflow:
  image:
    repository: apache/airflow
    tag: 2.8.1-python3.10
    pullPolicy: IfNotPresent

  config:
    AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    AIRFLOW__OPENMETADATA__HOST: http://openmetadata:8585

  extraPipPackages:
    - openmetadata-ingestion==1.7.1.1
    - openmetadata-managed-apis==1.7.1.1
    - apache-airflow-providers-openlineage==2.3.0

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: Admin
      lastName: User

web:
  service:
    type: LoadBalancer
    port: 8080

logs:
  persistence:
    enabled: true
    storageClassName: azurefile-csi
    size: 1Gi

scheduler:
  logCleanup:
    enabled: false

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: postgres
  persistence:
    enabled: true
    size: 8Gi
