executor: KubernetesExecutor

images:
  airflow:
    repository: apache/airflow
    tag: 2.8.1
    pullPolicy: IfNotPresent
  
airflow:
  executor: KubernetesExecutor
  extraPipPackages:
    - apache-airflow-providers-openlineage==2.3.0
    - openmetadata-ingestion==1.7.1.1
    - openmetadata-managed-apis==1.7.1.1

config:
  AIRFLOW__CORE__EXECUTOR:
    value: KubernetesExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED:
    value: "True"
  AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE:
    value: "5"
  AIRFLOW__DATABASE__SQL_ALCHEMY_MAX_OVERFLOW:
    value: "10"
  AIRFLOW__API__AUTH_BACKEND:
    value : "airflow.api.auth.backend.basic_auth"
  AIRFLOW__OPENMETADATA__HOST:
    value: "http://openmetadata:8585"

webserver:
  waitForMigrations:
    enabled: False
  service:
    type: LoadBalancer
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60

scheduler:
  waitForMigrations:
    enabled: False
  livenessProbe:
    initialDelaySeconds: 60

logs:
  waitForMigrations:
    enabled: False
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: azurefile-csi

workers:
  waitForMigrations:
    enabled: False
  persistence:
    enabled: false

triggerer:
  waitForMigrations:
    enabled: False
  persistence:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: postgres
  primary:
    persistence:
      enabled: true
      size: 8Gi

users:
  - username: admin
    password: admin
    role: Admin
    email: admin@example.com
