executor: KubernetesExecutor

images:
  airflow:
    repository: daappoc25.azurecr.io/airflow
    tag: latest
    pullPolicy: IfNotPresent

airflow:
  config:
    AIRFLOW__OPENMETADATA__API_VERSION: "v1"
    AIRFLOW__METRICS__METRICS_USE_PATTERN_MATCH: "True"
    AIRFLOW__CORE__AUTH_MANAGER: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager" 
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@airflow-postgresql:5432/airflow_db

  initContainers:
    - name: wait-for-airflow-migrations
      image: daappoc25.azurecr.io/airflow:latest
      imagePullPolicy: IfNotPresent
      command:
        - bash
        - -c
        - |
          airflow db migrate || echo "Migration likely already applied"


  env:
    - name: AIRFLOW__OPENMETADATA__HOST
      value: "http://128.85.217.88:8585"
    - name: AIRFLOW__OPENMETADATA__API_VERSION
      value: "v1"
    - name: AIRFLOW__API__AUTH_BACKENDS
      value: "airflow.api.auth.backend.basic_auth"

  extraVolumeMounts:
    - name: airflow-plugins
      mountPath: /opt/airflow/plugins

  webserver:
    service:
      type: LoadBalancer
      port: 8080  
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1

  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi

  workers:
    replicas: 1
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: managed-csi
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m

  triggerer:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: managed-csi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false

  dags:
    persistence:
      enabled: false
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: managed-csi

  logs:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: managed-csi

  initContainers:
    - name: wait-for-airflow-migrations
      image: daappoc25.azurecr.io/airflow:latest
      imagePullPolicy: IfNotPresent
      command:
        - bash
        - -c
        - |
          airflow db check-migrations --migration-wait-timeout=60 || echo "Migration already done or timed out"


postgresql:
  enabled: true 
  auth:
    username: admin 
    password: admin 
    database: airflow_db 
  primary:
    persistence:
      enabled: true
      size: 2Gi 
      storageClass: managed-csi 
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m