# airflow-values.yaml
images:
    airflow:
      repository: "apache/airflow"
      tag: "2.7.3-python3.11"  # Use Airflow 2.7.3
      pullPolicy: Always

airflow:
  executor: KubernetesExecutor

  extraInitContainers:
    - name: install-openmetadata
      image: apache/airflow:2.7.3-python3.11  # Match the main image version
      command:
        - "sh"
        - "-c"
        - |
          pip install --no-cache-dir \
            "openmetadata-ingestion[airflow]==1.3.2.0" \
            "openmetadata-managed-apis==1.3.2.0"
      volumeMounts:
        - mountPath: /opt/airflow/plugins
          name: airflow-plugins

  extraEnv:
    - name: AIRFLOW__OPENMETADATA__HOST
      value: "http://openmetadata.daap-dev.svc.cluster.local:8585"
    - name: AIRFLOW__OPENMETADATA__AUTH_PROVIDER
      value: "no-auth"
    - name: AIRFLOW__OPENMETADATA__API_VERSION
      value: "v1"
    - name: AIRFLOW__API__AUTH_BACKEND
      value: "airflow.api.auth.backend.basic_auth"

  extraVolumeMounts:
    - name: airflow-plugins
      mountPath: /opt/airflow/plugins

  extraVolumes:
    - name: airflow-plugins
      persistentVolumeClaim:
        claimName: airflow-plugins-pvc  # Use a Persistent Volume

  # Scheduler Configuration
  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  # Webserver Configuration
  web:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    service:
      type: ClusterIP

  # Logs, DAGs, Worker, and Triggerer Persistence
  dags:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
  logs:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
  workers:
    resources:
      limits:
        memory: "2Gi"  
    requests:
        memory: "1Gi"  
  
  triggerer:
    persistence:
      enabled: true
      size: 500Mi

  # Database Configuration
  postgresql:
    enabled: true
    postgresqlDatabase: "airflow"
    postgresqlUsername: "airflow"
    postgresqlPassword: "airflow"
    persistence:
      size: 1Gi