executor: KubernetesExecutor

images:
  airflow:
    repository: daappoc25.azurecr.io/airflow
    tag: ver-1
    pullPolicy: IfNotPresent
  
airflow:
  executor: KubernetesExecutor

config:
  AIRFLOW__CORE__EXECUTOR:
    value: KubernetesExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED:
    value: "True"
  AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE:
    value: "5"
  AIRFLOW__DATABASE__SQL_ALCHEMY_MAX_OVERFLOW:
    value: "10"
  AIRFLOW__API__AUTH_BACKEND:
    value : "airflow.api.auth.backend.basic_auth"
  AIRFLOW__OPENMETADATA__HOST:
    value: "http://openmetadata:8585"
  AIRFLOW__CORE__AUTH_MANAGER:
    value: "airflow.auth.managers.fab.fallback_auth_manager.FallbackAuthManager"

webserver:
  service:
    type: LoadBalancer
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60

scheduler:
  livenessProbe:
    initialDelaySeconds: 60

logs:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: azurefile-csi

workers:
  persistence:
    enabled: false

triggerer:
  persistence:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: postgres
  primary:
    persistence:
      enabled: true
      size: 8Gi

users:
  - username: admin
    password: admin
    role: Admin
    email: admin@example.com
