airflow:
  executor: KubernetesExecutor

  images:
    airflow:
      repository: "apache/airflow"
      tag: "2.7.3-python3.11"
      pullPolicy: Always

  extraPipPackages:
    - openmetadata-airflow==1.0
    - openmetadata-ingestion==1.6.6.2

  extraEnv:
    - name: PYTHONPATH
      value: "/opt/airflow/plugins:/home/airflow/.local/lib/python3.11/site-packages:/usr/local/lib/python3.11/site-packages:$PYTHONPATH"
    - name: AIRFLOW__OPENMETADATA__HOST
      value: "http://openmetadata.daap-dev.svc.cluster.local:8585"
    - name: AIRFLOW__OPENMETADATA__AUTH_PROVIDER
      value: "no-auth"
    - name: AIRFLOW__OPENMETADATA__API_VERSION
      value: "v1"
    - name: AIRFLOW__API__AUTH_BACKEND
      value: "airflow.api.auth.backend.basic_auth"

  extraVolumeMounts:
    - name: airflow-plugins
      mountPath: /opt/airflow/plugins

  extraVolumes:
    - name: airflow-plugins
      emptyDir: {}

  scheduler:
    replicas: 1
    extraVolumeMounts:
      - name: airflow-plugins
        mountPath: /opt/airflow/plugins
    extraVolumes:
      - name: airflow-plugins
        emptyDir: {}
    extraEnv:
      - name: PYTHONPATH
        value: "/opt/airflow/plugins:/home/airflow/.local/lib/python3.11/site-packages:/usr/local/lib/python3.11/site-packages:$PYTHONPATH"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  web:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    service:
      type: ClusterIP


  postgresql:
    enabled: true
    postgresqlDatabase: "airflow"
    postgresqlUsername: "airflow"
    postgresqlPassword: "airflow"
    persistence:
      size: 1Gi

  dags:
    persistence:
      enabled: true
      size: 500Mi  
      accessModes:
        - ReadWriteOnce
  logs:
    persistence:
      enabled: true
      size: 500Mi 
      accessModes:
        - ReadWriteOnce
  workers:
    persistence:
      enabled: true
      size: 500Mi
  triggerer:
    persistence:
      enabled: true
      size: 500Mi

persistence:
  enabled: true  
  size: 1Gi
  accessModes: 
    - ReadWriteOnce
