airflow:
  images:
    airflow:
      repository: "apache/airflow"
      tag: "2.8.1-python3.11"  
      pullPolicy: IfNotPresent

  extraPipPackages:
    - "openmetadata-ingestion==1.3.0"     
    - "openmetadata-airflow==1.3.0" 
    - "apache-airflow-providers-http"

  config: 
    AIRFLOW__OPENMETADATA__HOST: "http://openmetadata.daap-dev.svc.cluster.local:8585"
    AIRFLOW__OPENMETADATA__AUTH_PROVIDER: "no-auth"
    AIRFLOW__OPENMETADATA__API_VERSION: "v1"
    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"

  # Scheduler Configuration
  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  # Webserver Configuration 
  web:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    service:
      type: ClusterIP

  # Logs, DAGs, Worker, and Triggerer Persistence 
  dags:
    persistence:
      enabled: true
      size: 500Mi  
      accessModes:
        - ReadWriteOnce
  logs:
    persistence:
      enabled: true
      size: 500Mi 
      accessModes:
        - ReadWriteOnce
  workers:
    persistence:
      enabled: true
      size: 500Mi
  triggerer:
    persistence:
      enabled: true
      size: 500Mi

  # Database Configuration 
  postgresql:
    enabled: true
    postgresqlDatabase: "airflow"
    postgresqlUsername: "airflow"
    postgresqlPassword: "airflow"
    persistence:
      size: 1Gi
