executor: KubernetesExecutor

images:
  airflow:
    repository: daappoc25.azurecr.io/airflow
    tag: latest
    pullPolicy: IfNotPresent


config:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED: "True"
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE: "5"
    AIRFLOW__DATABASE__SQL_ALCHEMY_MAX_OVERFLOW: "10"
    AIRFLOW__OPENMETADATA__HOST: "http://openmetadata:8585"

webserver:
  service:
    type: LoadBalancer
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60

scheduler:
  livenessProbe:
    initialDelaySeconds: 60

logs:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: azurefile-csi

workers:
  persistence:
    enabled: false
triggerer:
  persistence:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: postgres
  primary:
    persistence:
      enabled: true
      size: 8Gi

users:
  - username: admin
    password: admin
    role: Admin
    email: admin@example.com
