airflow:
  executor: KubernetesExecutor

  extraEnv:
    - name: AIRFLOW__OPENMETADATA__HOST
      value: "http://48.211.236.64:8585"
    - name: AIRFLOW__OPENMETADATA__API_VERSION
      value: "v1"

  extraVolumeMounts:
    - name: airflow-plugins
      mountPath: /opt/airflow/plugins

  # Scheduler Configuration
  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  # Webserver Configuration
  web:
    service:
        type: LoadBalancer  
        port: 8080
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  # Logs, DAGs, Worker, and Triggerer Persistence
  dags:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: standard

  logs:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: standard

  workers:
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  triggerer:
    persistence:
      enabled: true
      size: 500Mi

  # Database Configuration
  postgresql:
    enabled: false  # Set to true only if need an internal PostgreSQL DB
