airflow:
  executor: "KubernetesExecutor"
  defaultAirflowRepository: "apache/airflow"
  defaultAirflowTag: "2.7.1"

  # Scheduler Configuration
  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    persistence:
      enabled: true
      size: 1Gi

  # Webserver Configuration 
  web:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    service:
      type: ClusterIP

  # Logs, DAGs, Worker, and Triggerer Persistence 
  dags:
    persistence:
      enabled: true
      size: 500Mi  
      accessModes:
        - ReadWriteOnce
  logs:
    persistence:
      enabled: true
      size: 500Mi 
      accessModes:
        - ReadWriteOnce
  workers:
    persistence:
      enabled: true
      size: 500Mi
  triggerer:
    persistence:
      enabled: true
      size: 500Mi

  # Database Configuration 
  postgresql:
    enabled: true
    postgresqlDatabase: "airflow"
    postgresqlUsername: "airflow"
    postgresqlPassword: "airflow"
    persistence:
      size: 1Gi

  # Redis Configuration 
  redis:
    enabled: true
    master:
      persistence:
        size: 1Gi
