airflow:
  executor: KubernetesExecutor

  config:
    AIRFLOW__OPENMETADATA__API_VERSION: "v1"
    AIRFLOW__METRICS__METRICS_USE_PATTERN_MATCH: "True"
    AIRFLOW__CORE__AUTH_MANAGER: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://admin:admin@airflow-postgresql:5432/airflow_db"
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED: "True"
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE: "5"
    AIRFLOW__DATABASE__SQL_ALCHEMY_MAX_OVERFLOW: "10"

  extraPipPackages:
    - "apache-airflow-providers-fab==4.4.0"
    - "apache-airflow-providers-postgres==5.7.0"
    - "apache-airflow-providers-cncf-kubernetes==7.4.0"
    - "psycopg2-binary==2.9.7"

  env:
    - name: AIRFLOW__OPENMETADATA__HOST
      value: "http://128.85.217.88:8585"
    - name: AIRFLOW__OPENMETADATA__API_VERSION
      value: "v1"

  extraVolumeMounts:
    - name: airflow-plugins
      mountPath: /opt/airflow/plugins"

  webserver:
    service:
      type: LoadBalancer
      port: 8080  
    startupProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 90
      timeoutSeconds: 20
      periodSeconds: 10
      failureThreshold: 10
    waitForMigrations:
      enabled: false
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1

  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi

  workers:
    replicas: 1
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: managed-csi
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m

  triggerer:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: managed-csi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false

  dags:
    persistence:
      enabled: false
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: managed-csi

  logs:
    persistence:
      enabled: true
      size: 500Mi
      accessModes:
        - ReadWriteOnce
      storageClassName: managed-csi

postgresql:
  enabled: true 
  auth:
    username: admin 
    password: admin 
    database: airflow_db 
  primary:
    persistence:
      enabled: true
      size: 2Gi 
      storageClass: managed-csi 
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m