apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-upgrade
  namespace: daap-dev
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: daappoc25.azurecr.io/airflow:latest
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args:
            - |
              airflow db upgrade && airflow users create \
                --username admin \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com \
                --password admin
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED
              value: "True"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE
              value: "5"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_MAX_OVERFLOW
              value: "10"
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://postgres:postgres@airflow-postgresql:5432/airflow
