executor: KubernetesExecutor

webserver:
  service:
    type: LoadBalancer
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60

scheduler:
  livenessProbe:
    initialDelaySeconds: 60

triggerer:
  persistence:
    enabled: false
    size: 1Gi

workers:
  persistence:
    enabled: false
    size: 1Gi

logs:
  persistence:
    enabled: true
    size: 1Gi

postgresql:
  enabled: false

airflow:
  image:
    repository: apache/airflow
    tag: 2.10.5-python3.11
    pullPolicy: IfNotPresent

  config:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor

    # Use MySQL instead of Postgres
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "mysql+mysqldb://openmetadata_user:openmetadata123@mysql.daap-dev.svc.cluster.local:3306/airflow_db"

    # Optional but recommended DB config tuning
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED: "True"
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE: "5"
    AIRFLOW__DATABASE__SQL_ALCHEMY_MAX_OVERFLOW: "10"

    # For OpenMetadata Integration (adjust if needed)
    AIRFLOW__OPENMETADATA__HOST: "http://openmetadata:8585"

  extraPipPackages:
    - openmetadata-ingestion==1.7.1.1
    - apache-airflow-providers-openlineage==2.3.0
    - apache-airflow-providers-fab==4.4.0
    - apache-airflow-providers-mysql==4.3.0
    - mysqlclient==2.2.0  

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
