airflow:
  executor: KubernetesExecutor

  images:
    airflow:
      repository: "apache/airflow"
      tag: "2.8.1-python3.11"
      pullPolicy: Always

  extraInitContainers:
    - name: install-openmetadata
      image: apache/airflow:2.8.1-python3.11
      command:
        - "sh"
        - "-c"
        - |
          pip install --no-cache-dir "openmetadata-ingestion[airflow]" "openmetadata-airflow==1.0"
      volumeMounts:
        - mountPath: /opt/airflow/plugins
          name: airflow-plugins

  extraEnv:
    - name: AIRFLOW__OPENMETADATA__HOST
      value: "http://openmetadata.daap-dev.svc.cluster.local:8585"
    - name: AIRFLOW__OPENMETADATA__AUTH_PROVIDER
      value: "no-auth"
    - name: AIRFLOW__OPENMETADATA__API_VERSION
      value: "v1"
    - name: AIRFLOW__API__AUTH_BACKEND
      value: "airflow.api.auth.backend.basic_auth"
  extraPipPackages:
    - "openmetadata-managed-apis==1.3.2" 

  extraVolumeMounts:
    - name: airflow-plugins
      mountPath: /opt/airflow/plugins

  extraVolumes:
    - name: airflow-plugins
      emptyDir: {}

  # Scheduler Configuration
  scheduler:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  # Webserver Configuration 
  web:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    service:
      type: ClusterIP

  # Logs, DAGs, Worker, and Triggerer Persistence 
  dags:
    persistence:
      enabled: true
      size: 500Mi  
      accessModes:
        - ReadWriteOnce
  logs:
    persistence:
      enabled: true
      size: 500Mi 
      accessModes:
        - ReadWriteOnce
  workers:
    persistence:
      enabled: true
      size: 500Mi
  triggerer:
    persistence:
      enabled: true
      size: 500Mi

  # Database Configuration 
  postgresql:
    enabled: true
    postgresqlDatabase: "airflow"
    postgresqlUsername: "airflow"
    postgresqlPassword: "airflow"
    persistence:
      size: 1Gi
