executor: KubernetesExecutor

airflow:
  image:
    repository: openmetadata/ingestion
    tag: 1.7.1
    pullPolicy: IfNotPresent

  extraEnv:
    - name: AIRFLOW__CORE__FERNET_KEY
      valueFrom:
        secretKeyRef:
          name: airflow-secrets
          key: FERNET_KEY
    - name: AIRFLOW__WEBSERVER__SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: airflow-secrets
          key: SECRET_KEY

  config:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgresql/airflow

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: Air
      lastName: Flow

web:
  service:
    type: LoadBalancer
    port: 8080

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

redis:
  enabled: true

logs:
  persistence:
    enabled: true
    storageClassName: azurefile
    size: 1Gi

dags:
  persistence:
    enabled: true
    storageClassName: azurefile
    size: 1Gi

triggerer:
  enabled: true
