executor: KubernetesExecutor

webserver:
  service:
    type: LoadBalancer
  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "1Gi"
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60

scheduler:
  livenessProbe:
    initialDelaySeconds: 60

triggerer:
  persistence:
    enabled: false

workers:
  persistence:
    enabled: false

logs:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: azurefile-csi

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: airflow
  primary:
    persistence:
      enabled: true
      size: 8Gi

airflow:
  image:
    repository: daappoc25.azurecr.io/airflow
    tag: latest
    pullPolicy: IfNotPresent

  config:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED: "True"
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE: "5"
    AIRFLOW__DATABASE__SQL_ALCHEMY_MAX_OVERFLOW: "10"
    AIRFLOW__OPENMETADATA__HOST: "http://openmetadata:8585"

  extraPipPackages:
    - openmetadata-ingestion==1.7.1.1
    - apache-airflow-providers-openlineage==2.3.0
    - mysqlclient==2.2.0
    - psycopg2-binary==2.9.9

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com

migrateDatabase: false  # Do not run migrations automatically
