apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Fixing permissions..."
              chown -R 1001:1001 /bitnami/mysql/data
          volumeMounts:
            - name: mysql-data
              mountPath: /bitnami/mysql/data
          securityContext:
            runAsUser: 0
      containers:
        - name: mysql
          image: bitnami/mysql:9.3.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: yourRootPasswordHere
            - name: MYSQL_DATABASE
              value: yourDatabaseName
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /bitnami/mysql/data
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName:  managed-csi
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
