apiVersion: v1
kind: Secret
metadata:
  name: opensearch-secret
  namespace: daap-dev
type: Opaque
data:
  username: b3BlbnNlYXJjaA==          # base64 of 'opensearch'
  password: b3BlbnNlYXJjaHBhc3M=      # base64 of 'opensearchpass'
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: daap-dev
spec:
  selector:
    app: opensearch
  ports:
    - port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: daap-dev
spec:
  serviceName: "opensearch"
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.12.0
          env:
            - name: discovery.type
              value: single-node
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: opensearch-secret
                  key: username
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-secret
                  key: password
          ports:
            - containerPort: 9200
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: opensearch-pv
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9200
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9200
            initialDelaySeconds: 20
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: opensearch-pv
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: default
        resources:
          requests:
            storage: 1Gi
