openmetadata:
  image:
    repository: docker.getcollate.io/openmetadata/openmetadata
    tag: latest
  service:
    type: LoadBalancer

  config:
    elasticsearch:
      host: http://opensearch-cluster-master:9200
      type: opensearch
    database:
      host: openmetadata-mysql
      port: 3306
      username: root
      password: mysqlrootpass
      scheme: mysql
      database: openmetadata_db

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    storageClass: managed-csi
