clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: ClusterIP  
  port: 9200

persistence:
  enabled: true  
  size: 1Gi
  accessModes:
    - ReadWriteOnce

replicas: 1  

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    memory: "3Gi"

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xmx2g -Xms2g"
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "DaapOpenSrhAdmn01$"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"

config:
    opensearch.yml: |
      plugins.security.disabled: true
      network.host: 0.0.0.0

securityConfig:
  enabled: false
 
startupProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 300   
  periodSeconds: 20
  failureThreshold: 15

