image:
  repository: docker.getcollate.io/openmetadata/openmetadata
  tag: latest
  pullPolicy: Never

service:
  type: LoadBalancer

config:
  database:
    host: openmetadata-mysql
    port: 3306
    scheme: mysql
    username: root
    password: mysqlrootpass
    database: openmetadata_db

  elasticsearch:
    host: http://opensearch.daap-dev.svc.cluster.local:9200
    type: opensearch
    username: admin
    password: DaapOpenSrhAdmn01$


persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClass: managed-csi

mysql:
  enabled: true
  auth:
    rootPassword: mysqlrootpass
    database: openmetadata_db
  primary:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: managed-csi
  image:
    repository: bitnami/mysql
    tag: 8.0
