clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: ClusterIP  
  port: 9200

persistence:
  enabled: false  

replicas: 1  


resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1000m"

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xmx512m -Xms512m" 
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "ElasticSearch@Ad100"
# persistence:
#   enabled: true
#   size: "4Gi"  # Adjust size as needed
startupProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 300   # Wait for 5 minutes
  periodSeconds: 20
  failureThreshold: 15