clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: ClusterIP  
  port: 9200

persistence:
  enabled: false  

replicas: 1  

extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"
  - name: plugins.security.ssl.http.enabled
    value: "false"     
  - name: plugins.security.disabled
    value: "true"     
  - name: "network.host"
    value: "0.0.0.0" 
  - name: "discovery.type"
    value: "single-node"
  - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
    value: "admin"

resources:
  requests:
    memory: "500Mi" 
    cpu: "250m"     
  limits:
    memory: "1Gi"    
    cpu: "500m"      
