clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: LoadBalancer  
  port: 9200

persistence:
  enabled: false  

replicas: 1  

extraEnvs:
  - name: "network.host"
    value: "0.0.0.0"
  - name: "discovery.type"
    value: "single-node"
  - name: "DISABLE_INSTALL_DEMO_CONFIG"
    value: "true"
  - name: "DISABLE_SECURITY_PLUGIN"
    value: "true"
  - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
    value: "admin"
  - name: "OPENSEARCH_JAVA_OPTS"
    value: "-Xmx2G -Xms2G" 

resources:
  requests:
    memory: "2Gi" 
    cpu: "1"     
  limits:
    memory: "4Gi"    
    cpu: "2"      

readinessProbe:   
  tcpSocket:
    port: 9200
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 10

startupProbe:     
  tcpSocket:
    port: 9200
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 30