clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: ClusterIP  
  port: 9200

persistence:
  enabled: false  

replicas: 1  


resources:
  requests:
    memory: "2Gi"  
    cpu: "500m"
  limits:
    memory: "4Gi"  
    cpu: "1"

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xmx1G -Xms1G"  
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "ElasticSearch@Ad100"
# persistence:
#   enabled: true
#   size: "4Gi"  # Adjust size as needed