clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  # This is what OpenMetadata will use as `host`
  type: ClusterIP  # OpenSearch should not be exposed externally
  port: 9200

persistence:
  enabled: false  # Change to true if using persistent storage

replicas: 1  # Number of OpenSearch nodes (increase for HA)

extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"

resources:
  requests:
    memory: "500Mi" 
    cpu: "250m"     
  limits:
    memory: "1Gi"    
    cpu: "500m"      
