image:
  repository: daappoc25.azurecr.io/openmetadata
  tag: custom
  pullPolicy: IfNotPresent

extraInitContainers:
  - name: bootstrap-init
    image: daappoc25.azurecr.io/openmetadata:custom
    command: ["/bin/bash", "-c"]
    args: ["/app/custom-bootstrap/bootstrap_storage.sh"]


service:
  type: LoadBalancer

config:
  database:
    host: mysql.daap-dev.svc.cluster.local
    port: 3306
    enabled: true
    driverClass: com.mysql.cj.jdbc.Driver
    dbScheme: mysql
    databaseName: openmetadata_db
    auth:
      username: openmetadata_user
      password:
        secretRef: mysql-secrets
        secretKey: openmetadata-mysql-password
    dbParams: "allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"

  elasticsearch:
    host: opensearch-cluster-master.daap-dev.svc.cluster.local
    type: opensearch
    username: admin
    password: DaapOpenSrhAdmn01$


persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClass: managed-csi

