clusterName: "opensearch-cluster"

image:
  repository: opensearchproject/opensearch
  tag: "2.12.0"
  pullPolicy: IfNotPresent

replicas: 1

service:
  name: opensearch-cluster-master
  type: ClusterIP
  port: 9200

persistence:
  enabled: true
  size: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClass: managed-csi

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "4Gi"

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"
  - name: DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI
    value: "true"

config:
  opensearch.yml: |
    cluster.name: "opensearch-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node
    plugins.security.disabled: true
    node.roles: [cluster_manager, data, ingest]


startupProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 5

readinessProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 5

livenessProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 5

opensearch:
  security:
    enabled: false
    tls:
      enabled: false
      autoGenerated: false
