clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: ClusterIP  
  port: 9200

persistence:
  enabled: false  

replicas: 1  


resources:
  requests:
    memory: "2Gi"  
    cpu: "250m"
  limits:
    memory: "4Gi"  
    cpu: "500m"

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xmx512m -Xms512m" 
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "ElasticSearch@Ad100"
# persistence:
#   enabled: true
#   size: "4Gi"  # Adjust size as needed
startup:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 60  # Wait 60 seconds before starting the probe
  periodSeconds: 20        # Check every 20 seconds
  failureThreshold: 10      # Allow up to 10 failures