apiVersion: v1
kind: Secret
metadata:
  name: opensearch-secret
  namespace: daap-dev
type: Opaque
stringData:
  username: admin
  password: DaapOpenSrhAdmn01$

---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: daap-dev
spec:
  selector:
    app: opensearch
  ports:
    - port: 9200
      targetPort: 9200
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: daap-dev
spec:
  serviceName: "opensearch"
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.12.0
          env:
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-secret
                  key: password
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: DISABLE_SECURITY_PLUGIN
              value: "false"  # set to true only if you want unauthenticated access
          ports:
            - containerPort: 9200
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - name: opensearch-pv
              mountPath: /usr/share/opensearch/data
          livenessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 20
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: opensearch-pv
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: default
        resources:
          requests:
            storage: 1Gi
