clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: ClusterIP  
  port: 9200

persistence:
  enabled: false  

replicas: 1  


resources:
  requests:
    memory: "500m"
  limits:
    memory: "1Gi"

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xmx2g -Xms2g" 
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "ElasticSearch@Ad100"
 
startupProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 300   #  5 minutes lag
  periodSeconds: 20
  failureThreshold: 15

config:
  opensearch.yml: |
    plugins.security.disabled: true  