clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: ClusterIP  
  port: 9200

persistence:
  enabled: false  

replicas: 1  


resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "ElasticSearch@Ad100"

# livenessProbe:
#   httpGet:
#     path: /
#     port: 9200
#   initialDelaySeconds: 60  
#   periodSeconds: 20
#   failureThreshold: 30

# startupProbe:
#   httpGet:
#     path: /
#     port: 9200
#   initialDelaySeconds: 60  
#   periodSeconds: 20
#   failureThreshold: 30