image:
  repository: daappoc25.azurecr.io/openmetadata
  tag: custom
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer

config:
  database:
    host: mysql.daap-dev.svc.cluster.local
    port: 3306
    enabled: true
    driverClass: com.mysql.cj.jdbc.Driver
    dbScheme: mysql
    databaseName: openmetadata_db
    auth:
      username: openmetadata_user
      password:
        secretRef: mysql-secrets
        secretKey: openmetadata-mysql-password
    dbParams: "allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"

  elasticsearch:
    host: opensearch-cluster-master.daap-dev.svc.cluster.local
    type: opensearch
    username: admin
    password: DaapOpenSrhAdmn01$


persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClass: managed-csi

# mysql:
#   enabled: true
#   auth:
#     rootPassword: mysqlrootpass
#     database: openmetadata_db
#     username: openmetadata_user
#     password: openmetadata123 
#   primary:
#     persistence:
#       enabled: true
#       size: 1Gi
#       storageClass: managed-csi
#   image:
#     repository: bitnami/mysql
#     tag: 8.0
