clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: ClusterIP  
  port: 9200

persistence:
  enabled: false  

replicas: 1  

extraEnvs:
  - name: "network.host"
    value: "0.0.0.0"
  - name: "discovery.type"
    value: "single-node"
  - name: "DISABLE_INSTALL_DEMO_CONFIG"
    value: "true"
  - name: "DISABLE_SECURITY_PLUGIN"
    value: "true"


resources:
  requests:
    memory: "1Gi" 
    cpu: "500m"     
  limits:
    memory: "2Gi"    
    cpu: "1"      
