clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master  
  type: ClusterIP  
  port: 9200

persistence:
  enabled: false  

replicas: 1  


resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1000m"

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xmx2g -Xms2g" 
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "ElasticSearch@Ad100"
 
startupProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 300   #  5 minutes lag
  periodSeconds: 20
  failureThreshold: 15

config:
  opensearch.yml: |
    plugins.security.disabled: true  

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opensearch-sysctl
  namespace: kube-system
  labels:
    app: opensearch-sysctl
spec:
  selector:
    matchLabels:
      name: opensearch-sysctl
  template:
    metadata:
      labels:
        name: opensearch-sysctl
    spec:
      containers:
      - name: sysctl
        image: busybox
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144 && sleep infinity"]
        securityContext:
          privileged: true
      restartPolicy: Always