clusterName: opensearch
nodeGroup: master

replicaCount: 1

roles:
  master: "true"
  ingest: "true"
  data: "true"

persistence:
  enabled: true
  size: 1Gi
  storageClass: default

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

opensearchJavaOpts: "-Xms512m -Xmx512m"

securityConfig:
  enabled: true
  createSecret: true
  secret:
    name: opensearch-secret

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-secret
        key: password

startupProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 30   
  periodSeconds: 10
  failureThreshold: 5

config:
  opensearch.yml: |
    cluster.name: opensearch
    network.host: 0.0.0.0
    node.name: opensearch-single
    discovery.type: single-node
    plugins.security.disabled: false

---

apiVersion: v1
kind: Secret
metadata:
  name: opensearch-secret
  namespace: daap-dev
type: Opaque
stringData:
  username: admin
  password: DaapOpenSrhAdmn01$
