clusterName: "opensearch-cluster"

image:
  repository: opensearchproject/opensearch
  tag: "2.12.0"
  pullPolicy: IfNotPresent

replicas: 1

service:
  name: opensearch-cluster-master
  type: ClusterIP
  port: 9200

persistence:
  enabled: true
  size: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClass: managed-csi

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    memory: "3Gi"

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xms1024m -Xmx1024m"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  - name: DISABLE_SECURITY_PLUGIN
    value: "false"
  - name: DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI
    value: "true"

config:
  opensearch.yml: |
    plugins:
      security:
        disabled: false
    network.host: 0.0.0.0
    cluster.name: opensearch-cluster


startupProbe:
securityConfig:
  enabled: true
  create: true
  adminPassword: "DaapOpenSrhAdmn01$"  

startupProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 30   
  periodSeconds: 10
  failureThreshold: 5