clusterName: "opensearch-cluster"

service:
  name: opensearch-cluster-master
  type: ClusterIP  
  port: 9200



persistence:
  enabled: true  
  size: 1Gi
  accessModes:
    - ReadWriteOnce

replicas: 1  

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    memory: "2Gi"

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xmx3g -Xms3g"
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "DaapOpenSrhAdmn01$"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"

config:
  opensearch.yml: |
    plugins:
      security:
        disabled: false
    network.host: 0.0.0.0
    cluster.name: opensearch-cluster

securityConfig:
  enabled: true
  create: true
  adminPassword: "DaapOpenSrhAdmn01$"  

startupProbe:
  tcpSocket:
    port: 9200
  initialDelaySeconds: 30   
  periodSeconds: 10
  failureThreshold: 5

