name: Deploy OpenMetadata to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubectl Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Helm Repositories (If Not Added)
        run: |
          helm repo add open-metadata https://helm.open-metadata.org || true
          helm repo add opensearch https://opensearch-project.github.io/helm-charts || true
          helm repo add apache-airflow https://airflow.apache.org || true
          helm repo update

      - name: Deploy OpenSearch
        run: |
          helm upgrade --install opensearch opensearch/opensearch --namespace daap-dev  -f $(pwd)/charts/openmetadata/values-opensearch.yaml
          kubectl apply -f $(pwd)/charts/openmetadata/opensearch-sysctl-daemonset.yaml -n daap-dev

      - name: Deploy Airflow
        run: |
          kubectl apply -f $(pwd)/charts/openmetadata/airflow-plugins-pvc.yaml -n daap-dev
          helm upgrade --install airflow apache-airflow/airflow \
            --namespace daap-dev \
            --set logs.persistence.size=500Mi \
            --set triggerer.persistence.size=500Mi \
            --set workers.persistence.size=500Mi \
            --set images.airflow.repository=apache/airflow \
            --set images.airflow.tag=2.7.3-python3.11 \
            --set images.airflow.pullPolicy=Always \
            --set airflow.extraPipPackages[0]="openmetadata-ingestion[airflow]==1.3.2.0" \
            --set airflow.extraPipPackages[1]="openmetadata-managed-apis==1.3.2.0" \
            -f $(pwd)/charts/openmetadata/airflow-config.yaml
         


      - name: Deploy OpenMetadata
        run: |
          helm upgrade --install openmetadata open-metadata/openmetadata --namespace daap-dev -f $(pwd)/charts/openmetadata/values.yaml
         
