name: Deploy OpenMetadata to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubectl Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add OpenMetadata Helm Repo
        run: |
          helm repo add open-metadata https://helm.open-metadata.org
          helm repo update

      - name: Add OpenSearch Helm Repo
        run: |
          helm repo add opensearch https://opensearch-project.github.io/helm-charts
          helm repo update

      - name : Add Airflow Repo
        run: |
          helm repo add apache-airflow https://airflow.apache.org
          helm repo update

      - name: Deploy OpenSearch
        run: |
          helm upgrade --install opensearch opensearch/opensearch --namespace daap-dev  -f $(pwd)/charts/openmetadata/values-opensearch.yaml
          kubectl apply -f $(pwd)/charts/openmetadata/opensearch-sysctl-daemonset.yaml

      - name: Deploy Airflow
        run: |
          helm upgrade --install airflow apache-airflow/airflow --namespace daap-dev -f $(pwd)/charts/openmetadata/values.yaml

      - name: Deploy OpenMetadata
        run: |
          helm upgrade --install openmetadata open-metadata/openmetadata --namespace daap-dev -f $(pwd)/charts/openmetadata/values.yaml
