name: Deploy OpenMetadata to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubectl Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add OpenMetadata Helm Repo
        run: |
          helm repo add open-metadata https://helm.open-metadata.org
          helm repo update

      - name: Debug Helm Repos
        run: helm repo list

      - name: Check if values.yaml exists
        run: |
          ls -l $(pwd)/charts/openmetadata/
          if [ ! -f $(pwd)/charts/openmetadata/values.yaml ]; then echo "values.yaml not found!"; exit 1; fi

      - name: Deploy OpenSearch
        run: |
          helm repo add elastic https://helm.elastic.co
          helm repo update
          helm upgrade --install opensearch elastic/opensearch -n <namespace> -f $(pwd)/charts/opensearch/values.yaml
  
      - name: Deploy OpenMetadata
        run: |
          helm upgrade --install openmetadata open-metadata/openmetadata -f $(pwd)/charts/openmetadata/values.yaml
