name: Deploy OpenMetadata to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubectl Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Helm Repositories (If Not Added)
        run: |
          helm repo add open-metadata https://helm.open-metadata.org || true
          helm repo add opensearch https://opensearch-project.github.io/helm-charts || true
          helm repo add apache-airflow https://airflow.apache.org || true
          helm repo update

      - name: Deploy OpenSearch
        run: |
          helm upgrade --install opensearch opensearch/opensearch --namespace daap-dev  -f $(pwd)/charts/openmetadata/values-opensearch.yaml
          kubectl apply -f $(pwd)/charts/openmetadata/opensearch-sysctl-daemonset.yaml -n daap-dev

      - name: Deploy Airflow
        run: |
          helm upgrade --install airflow apache-airflow/airflow \
          --namespace daap-dev \
          --set logs.persistence.size=500Mi \
          --set triggerer.persistence.size=500Mi \
          --set workers.persistence.size=500Mi \
          -f $(pwd)/charts/openmetadata/airflow-config.yaml

      - name: Deploy OpenMetadata
        run: |
          helm upgrade --install openmetadata open-metadata/openmetadata --namespace daap-dev -f $(pwd)/charts/openmetadata/values.yaml
         
          # Step 2: Wait for OpenMetadata pod to be ready
          kubectl wait --namespace daap-dev \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/instance=openmetadata \
            --timeout=300s

          # Step 3: Trigger reindex (no interactive terminal needed)
          OPENMETADATA_POD=$(kubectl get pods -n daap-dev -l app.kubernetes.io/instance=openmetadata -o jsonpath='{.items[0].metadata.name}')
            kubectl exec -n daap-dev $OPENMETADATA_POD -- \
            bash -c "openmetadata-ops.sh reindex --force"
