name: Deploy OpenMetadata to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: charts/openmetadata
          file: charts/openmetadata/DockerAirflow
          push: true
          tags: ghcr.io/aniljith74/openmetadata-helm-chart-poc/airflow:custom

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubectl Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Helm Repositories
        run: |
          helm repo add open-metadata https://helm.open-metadata.org 
          helm repo add opensearch https://opensearch-project.github.io/helm-charts 
          helm repo add apache-airflow https://airflow.apache.org 
          helm repo update

      - name: Deploy OpenSearch if values-opensearch.yaml or opensearch-sysctl-daemonset.yaml changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE 'charts/openmetadata/(values-opensearch\.yaml|opensearch-sysctl-daemonset\.yaml)'; then
            echo "Changes detected in OpenSearch config files. Deploying OpenSearch..."
            helm upgrade --install opensearch opensearch/opensearch --namespace daap-dev -f $(pwd)/charts/openmetadata/values-opensearch.yaml
            kubectl apply -f $(pwd)/charts/openmetadata/opensearch-sysctl-daemonset.yaml -n daap-dev
          else
              echo "No changes in OpenSearch config. Skipping deployment."
          fi

      - name: Deploy MySQL if mysql.yaml changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'charts/openmetadata/mysql.yaml'; then
            echo "Changes detected in mysql.yaml. Applying MySQL manifest..."
            kubectl apply -f $(pwd)/charts/openmetadata/mysql.yaml -n daap-dev
          else
            echo "No changes in mysql.yaml. Skipping MySQL deployment."
          fi

      - name: Deploy OpenMetadata if values.yaml changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'charts/openmetadata/values.yaml'; then
            echo "Changes detected in OpenMetadata values.yaml. Deploying OpenMetadata..."
            helm upgrade --install openmetadata open-metadata/openmetadata --namespace daap-dev -f $(pwd)/charts/openmetadata/values.yaml
          else
            echo "No changes in OpenMetadata values.yaml. Skipping deployment."
          fi

      - name: Deploy Airflow if airflow-config.yaml changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'charts/openmetadata/airflow-config.yaml'; then
            echo "Changes detected in airflow-config.yaml. Deploying Airflow..."
            helm upgrade --install airflow apache-airflow/airflow \
            --version 1.10.0 \
            --namespace daap-dev \
            --set webserver.service.type=LoadBalancer \
            --set images.airflow.repository=ghcr.io/aniljith74/openmetadata-helm-chart-poc/airflow \
            --set images.airflow.tag=custom \
            --set images.airflow.pullPolicy=Always \
            --set workers.persistence.enabled=true \
            --set workers.persistence.size=1Gi \
            --set triggerer.persistence.enabled=true \
            --set triggerer.persistence.size=1Gi \
            -f $(pwd)/charts/openmetadata/airflow-config.yaml --reset-values

            kubectl set env deployment/airflow-webserver -n daap-dev \
            AIRFLOW__OPENMETADATA__HOST="http://135.222.170.7:8585" \
            AIRFLOW__OPENMETADATA__API_VERSION="v1" \
            AIRFLOW__API__AUTH_BACKENDS="airflow.api.auth.backend.basic_auth"
          else
            echo "No changes in airflow-config.yaml. Skipping Airflow deployment."
          fi

